# -*- coding: utf-8 -*-
"""Question 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19jhQ6zjSjJC732pqWD_M_lNz2DVDYRx4

Stage (t): Each coin denomination considered

State (s): The remaining amount of change still to be given (in cents), s = 0, 1, ..., 91

Action (x): The number of coins of the current denomination to use, x ≥ 0

State Transition Function:

s(t+1) = s(t) - x(t) × denomination(t)

Contribution Function:

C(s, x, t) = x (number of coins used at this stage)

DP Recursion (minimization):

f(s) = min over x { x + f(s - x × denom) }

Terminal Condition:

f(0) = 0 — no coins needed when change is fully given
"""

import pandas as pd

# ── Problem Parameters ───────────────────────────────────────────────────────
change_due = 91   # cents (2.00 - 1.09 = 0.91)

coins_standard = [50, 25, 10, 5, 1]
coins_with_20  = [50, 25, 20, 10, 5, 1]

# ── DP Solver ────────────────────────────────────────────────────────────────
def solve_coin_change(amount, coins, label):

    INF = float('inf')

    # f[s] = min number of coins to make s cents
    # coin_used[s] = which coin was used to achieve f[s]
    f         = [INF] * (amount + 1)
    coin_used = [0]   * (amount + 1)
    f[0]      = 0

    for s in range(1, amount + 1):
        for coin in coins:
            if coin <= s and f[s - coin] + 1 < f[s]:
                f[s]         = f[s - coin] + 1
                coin_used[s] = coin

    # ── Trace back the coins used ─────────────────────────────────────────────
    breakdown = {}
    remaining = amount
    while remaining > 0:
        coin = coin_used[remaining]
        breakdown[coin] = breakdown.get(coin, 0) + 1
        remaining      -= coin

    # ── Print results ─────────────────────────────────────────────────────────
    print("=" * 60)
    print(f"  {label}")
    print(f"  Coins available: {coins}")
    print(f"  Change to give:  {amount}¢")
    print("=" * 60)
    print(f"  Minimum number of coins: {f[amount]}")
    print("\n  Coin breakdown:")
    for coin in sorted(breakdown.keys(), reverse=True):
        print(f"    {coin:3d}¢  x {breakdown[coin]}  =  {coin * breakdown[coin]}¢")
    print(f"    {'TOTAL':>8}     =  {amount}¢")
    print()

    # ── Full DP table ─────────────────────────────────────────────────────────
    rows = []
    for s in range(amount + 1):
        rows.append({
            "Amount (¢)"       : s,
            "Min Coins f(s)"   : int(f[s]) if f[s] != INF else "∞",
            "Coin Used (¢)"    : coin_used[s] if f[s] != INF else "-"
        })
    df = pd.DataFrame(rows)
    print("  Full DP Table:")
    print(df.to_string(index=False))
    print()

    return f[amount], breakdown

# ── Part 1: Standard US coins ─────────────────────────────────────────────────
n1, b1 = solve_coin_change(change_due, coins_standard, "PART 1 — Standard US Coins")

# ── Part 2: General result ────────────────────────────────────────────────────
print("=" * 60)
print("  PART 2 — General Result")
print("=" * 60)
print("""
  The GREEDY ALGORITHM functions best for normal US coin values (1, 5, 10, 25, 50), according to the DP solution.

  This is due to the fact that US coins are "canonical," meaning that choosing the largest coin that fits would
  never result in a less-than-ideal outcome because each denomination is a multiple or near-multiple of smaller ones.

  Overall conclusion: The greedy method (always utilise the largest coin <= remaining amount) yields the fewest coins
  for canonical coin systems. DP thoroughly verifies this.
""")

# ── Part 3: With 20¢ coin ─────────────────────────────────────────────────────
n2, b2 = solve_coin_change(change_due, coins_with_20, "PART 3 — With Additional 20¢ Coin")

# ── Comparison ────────────────────────────────────────────────────────────────
print("=" * 60)
print("  COMPARISON SUMMARY")
print("=" * 60)
print(f"  Without 20¢ coin:  {n1} coins  → {b1}")
print(f"  With    20¢ coin:  {n2} coins  → {b2}")
if n2 < n1:
    print(f"\n  Adding the 20¢ coin saves {n1 - n2} coin(s)!")
elif n2 == n1:
    print(f"\n  Adding the 20¢ coin makes no difference for 91¢.")
print()

